data <- read.table(file='C:\\Users\\Phili\\Downloads\\smoking.txt')
head(data)
smoking_mod <- lm(status~trt,data=data)
library(DescTools)
PostHocTest(aov(smoking_mod), method = "lsd")
plot(resid(smoking_mod), type = "l")
plot(rstandard(smoking_mod)) + abline(h = 0)
data <- data %>% mutate(ntrt = ifelse(data$trt == "patchOnly", 1, 0))
plot(data$ntrt, rstandard(smoking_mod)) + abline(h = 0)
plot(data$status, rstandard(smoking_mod)) + abline(h = 0)
qqnorm(resid(smoking_mod))